apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: XXXX
  AWS_REGION: us-east-1
  AWS_SECRET_ACCESS_KEY: XXXX
  cloud: |
    [default]
    aws_access_key_id = XXX
    aws_secret_access_key = XXXX
kind: Secret
metadata:
  name: velero-credentials-secret
  namespace: velero
type: Opaque

