- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install jq package
  ansible.builtin.package:
    name: jq
    state: present

- name: install kubectl
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 700

- name: Download kustomize archive
  ansible.builtin.get_url:
    url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v{{ kustomize_version }}/kustomize_v{{ kustomize_version }}_linux_amd64.tar.gz
    dest: /tmp/kustomize_v{{ kustomize_version }}_linux_amd64.tar.gz
    mode: "0644"

- name: Extract kustomize binary
  ansible.builtin.unarchive:
    src: /tmp/kustomize_v{{ kustomize_version }}_linux_amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Install kustomize binary
  ansible.builtin.copy:
    src: /tmp/kustomize
    dest: /usr/local/bin/kustomize
    mode: "0755"
    remote_src: yes

- name: Create temporary directory for argo boot
  ansible.builtin.tempfile:
    state: directory
    suffix: values
  register: argotmpvalues

- name: Create temporary directory for external secrets
  ansible.builtin.tempfile:
    state: directory
    suffix: values
  register: extsectmpvalues

- name: "create directory for kubeconfig"
  ansible.builtin.file:
    path: "{{ kubeconfig_location }}"
    state: directory
    recurse: yes

- name: copy kubeconfig
  ansible.builtin.copy:
    src: "{{ kubeconfig_local_location }}/kubeconfig"
    dest: "{{ kubeconfig_location }}/kubeconfig"

- name: apply node labels
  ansible.builtin.shell: |
    kubectl --kubeconfig {{ kubeconfig_location }}/kubeconfig label --overwrite nodes {{ item.node_name }} {% for labels in lookup('dict', item.node_labels, wantlist=True) %} {{ labels.key }}={{ labels.value }}{% endfor %}
  loop: "{{ node_pool_labels }}"
  when: node_pool_labels is defined

- name: apply node taints
  ansible.builtin.shell: |
    kubectl --kubeconfig {{ kubeconfig_location }}/kubeconfig taint --overwrite nodes {{ item.node_name }} {% for taints in lookup('dict', item.node_taints, wantlist=True) %} {{ taints.value }}{% endfor %}
  loop: "{{ node_pool_taints }}"
  when: node_pool_taints is defined

- name: Upload ext secrets bootstrap files
  ansible.builtin.template:
    src: "templates/{{ item }}.yaml.j2"
    dest: "{{ extsectmpvalues.path }}/{{ item }}.yaml"
  with_items:
    - external-secretstore
    - external-secrets-netbird-patch
    - netbird-setupkey

- name: Upload argo bootstrap files
  ansible.builtin.template:
    src: "templates/{{ item }}.yaml.j2"
    dest: "{{ argotmpvalues.path }}/{{ item }}.yaml"
  with_items:
    - argocd-cm-patch
    - argocd-rbac-cm-patch
    - argo-gitlab
    - argo-root-app
    - argo-service-acct-patch
    - argocd-lovely-plugin
    - kustomization
    - namespace
    - vault-service-account-etc
    - vault-env
    - argo-oidc-secrets
    - argocd-server-patch
    - argocd-cmd-params-cm-patch
    - k8s-oidc-rbac
    - coredns-nodecache

- name: Install coredns-nodecache
  ansible.builtin.shell: |
    kubectl --kubeconfig {{ kubeconfig_location }}/kubeconfig apply -f {{ argotmpvalues.path }}/coredns-nodecache.yaml
  when: install_coredns | bool

- name: Install external-secrets
  ansible.builtin.shell: |
    helm repo add external-secrets https://charts.external-secrets.io
    helm --kubeconfig {{ kubeconfig_location }}/kubeconfig upgrade --install external-secrets external-secrets/external-secrets --version {{ external_secrets_version }} -n {{ external_secrets_namespace }} --create-namespace --set installCRDs=true

- name: Apply Netbird patch for external-secrets
  ansible.builtin.shell: |
    kubectl --kubeconfig {{ kubeconfig_location }}/kubeconfig apply -f {{ extsectmpvalues.path }}/netbird-setupkey.yaml
    kubectl --kubeconfig {{ kubeconfig_location }}/kubeconfig patch deployment external-secrets -n {{ external_secrets_namespace }} --patch-file {{ extsectmpvalues.path }}/external-secrets-netbird-patch.yaml
  when: netbird_sidecar_enabled | default(false) | bool

- name: Try clustersecretstore create until successful
  ansible.builtin.shell: kubectl --kubeconfig {{ kubeconfig_location }}/kubeconfig apply -n {{ external_secrets_namespace }} -f {{ extsectmpvalues.path }}/external-secretstore.yaml
  register: clustersecretstore
  until: clustersecretstore is not failed
  retries: 30
  delay: 10

- name: Install ArgoCD
  ansible.builtin.shell: |
    kustomize build {{ argotmpvalues.path }} > {{ argotmpvalues.path }}/argocd-deploy.yaml
    kubectl --kubeconfig {{ kubeconfig_location }}/kubeconfig apply -f {{ argotmpvalues.path }}/argocd-deploy.yaml
    kubectl --kubeconfig {{ kubeconfig_location }}/kubeconfig apply -f {{ argotmpvalues.path }}/argo-root-app.yaml

- name: copy kubeconfig for oidc and add credentials.
  ansible.builtin.shell: |
    cp {{ kubeconfig_location }}/kubeconfig {{ kubeconfig_location }}/{{ cluster_name }}-oidc-kubeconfig
    export KUBECONFIG={{ kubeconfig_location }}/{{ cluster_name }}-oidc-kubeconfig
    kubectl config delete-user admin
    kubectl config set-credentials oidc --exec-api-version=client.authentication.k8s.io/v1beta1 --exec-command=kubectl --exec-arg=oidc-login --exec-arg=get-token --exec-arg=--oidc-issuer-url={{ kubernetes_oidc_issuer }} --exec-arg=--oidc-client-id={{ kubernetes_oidc_client_id }} --exec-arg=--oidc-extra-scope=email --exec-arg=--oidc-extra-scope=offline_access --exec-arg=--oidc-extra-scope=profile --exec-arg=--oidc-extra-scope=openid
    kubectl config set-context $(kubectl config current-context) --user=oidc
  when: kubernetes_oidc_enabled | bool

- name: Fetch {{ cluster_name }}-oidc-kubeconfig
  ansible.builtin.fetch:
    src: "{{ kubeconfig_location }}/{{ cluster_name }}-oidc-kubeconfig"
    dest: "{{ kubeconfig_local_location }}/{{ cluster_name }}-oidc-kubeconfig"
    flat: yes
