- name: Disable argocd apps automated sync
  ansible.builtin.shell: |
    export KUBECONFIG={{ kubeconfig_location }}/kubeconfig
    kubectl patch application -n argocd root-app --type json --patch='[ { "op": "remove", "path": "/spec/syncPolicy/automated" } ]' || true
    for app in mojaloop-stateful-resources-app \
    common-stateful-resources-app; do
      kubectl patch application -n argocd $app --type json --patch='[ { "op": "remove", "path": "/spec/syncPolicy/automated" } ]' || true
    done
  args:
    executable: /bin/bash
  ignore_errors: true


- name: Get all RDSClusters in stateful-resources namespace
  ansible.builtin.shell: |
    export KUBECONFIG={{ kubeconfig_location }}/kubeconfig
    kubectl get RDSCluster -n stateful-resources -o jsonpath='{.items[*].metadata.name}'
  args:
    executable: /bin/bash
  register: rds_clusters
  changed_when: false

- name: Delete each RDSCluster one by one
  ansible.builtin.shell: |
    export KUBECONFIG={{ kubeconfig_location }}/kubeconfig
    kubectl delete RDSCluster {{ item }} -n stateful-resources --wait=false
  args:
    executable: /bin/bash
  loop: "{{ rds_clusters.stdout.split() }}"
  ignore_errors: true

- name: Get all DocDbClusters in stateful-resources namespace
  ansible.builtin.shell: |
    export KUBECONFIG={{ kubeconfig_location }}/kubeconfig
    kubectl get DocDbCluster -n stateful-resources -o jsonpath='{.items[*].metadata.name}'
  args:
    executable: /bin/bash
  register: docdb_clusters
  changed_when: false

- name: Delete each DocDbCluster one by one
  ansible.builtin.shell: |
    export KUBECONFIG={{ kubeconfig_location }}/kubeconfig
    kubectl delete DocDbCluster {{ item }} -n stateful-resources --wait=false
  args:
    executable: /bin/bash
  loop: "{{ docdb_clusters.stdout.split() }}"
  ignore_errors: true

- name: Wait for all RDSClusters to be deleted
  ansible.builtin.shell: |
    export KUBECONFIG={{ kubeconfig_location }}/kubeconfig
    kubectl get RDSCluster -n stateful-resources -o jsonpath='{.items}'
  args:
    executable: /bin/bash
  register: rds_check
  retries: 30
  delay: 10
  until: rds_check.stdout == "[]"
  failed_when: rds_check.rc != 0 and "NotFound" not in rds_check.stderr

- name: Wait for all DocDbClusters to be deleted
  ansible.builtin.shell: |
    export KUBECONFIG={{ kubeconfig_location }}/kubeconfig
    kubectl get DocDbCluster -n stateful-resources -o jsonpath='{.items}'
  args:
    executable: /bin/bash
  register: docdb_check
  retries: 30
  delay: 10
  until: docdb_check.stdout == "[]"
  failed_when: docdb_check.rc != 0 and "NotFound" not in docdb_check.stderr
