apiVersion: velero.io/v1
kind: Restore
metadata:
  name: storage-restore
  namespace: velero
spec:
  backupName: manual-trigger-20250724145042
  includeClusterResources: true
  includedNamespaces:
    - storage
  excludedResources:
    - validatingwebhookconfigurations.admissionregistration.k8s.io
    - mutatingwebhookconfigurations.admissionregistration.k8s.io
    - applications.argoproj.io
    - applicationset.argoproj.io
    - applicationset.argoproj.io/v1alpha1
    - applicationset.argoproj.io/v1alpha1/applicationsets
    - applicationset.argoproj.io/v1alpha1/applicationsettemplates
    - applicationset.argoproj.io/v1alpha1/applicationsettemplates/applicationsettemplates
    - applicationset.argoproj.io/v1alpha1/applicationsettemplates/applicationsettemplates/applicationsettemplates
    - applicationset.argoproj.io/v1alpha1/applicationsettemplates/applicationsettemplates/applicationsettemplates/applicationsettemplates
