{
 "title": "Mojaloop - ALS",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_uname_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Party Resource Metric Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ing GET /parties/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(moja_als_ing_getPartiesByTypeAndID_count{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum(moja_als_ing_getPartiesByTypeIDAndSubID_count{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Ing PUT /parties/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(moja_als_ing_putPartiesByTypeAndID_count{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum(moja_als_ing_putPartiesByTypeIDAndSubID_count{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Ing PUT /parties/*/error requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(moja_als_ing_putPartiesErrorByTypeAndID_count{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum(moja_als_ing_putPartiesErrorByTypeIDAndSubID_count{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "GET /parties/* Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 4 },
   "targets": [
    {
     "expr": "sum(moja_als_getPartiesByTypeAndID_count{success=\"true\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(moja_als_getPartiesByTypeAndID_count{success=\"false\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT /parties/* Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 4 },
   "targets": [
    {
     "expr": "sum(moja_als_putPartiesByTypeAndID_count{success=\"true\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(moja_als_putPartiesByTypeAndID_count{success=\"false\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT /parties/*/error Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "sum(moja_als_puttPartiesErrorByTypeAndID_count{success=\"true\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(moja_als_puttPartiesErrorByTypeAndID_count{success=\"false\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Party Resource Performance Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Party Handlers Ingress - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_als_ing_getPartiesByTypeAndID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_getPartiesByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "getPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_ing_putPartiesByTypeAndID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_putPartiesByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_ing_getPartiesByTypeIDAndSubID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_getPartiesByTypeIDAndSubID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "getPartiesByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_ing_putPartiesByTypeIDAndSubID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_putPartiesByTypeIDAndSubID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putPartiesByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_ing_putPartiesErrorByTypeAndID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_putPartiesErrorByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putPartiesErrorByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_ing_putPartiesErrorByTypeIDAndSubID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_putPartiesErrorByTypeIDAndSubID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putPartiesErrorByTypeIDAndSubID success:{{success}}"
    }
   ]
  },
  {
   "title": "Party Handler Ingress - Processing Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_als_ing_getPartiesByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "getPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_ing_putPartiesByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "putPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_ing_getPartiesByTypeIDAndSubID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "getPartiesByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_ing_putPartiesByTypeIDAndSubID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "putPartiesByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_ing_putPartiesErrorByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": " putPartiesErrorByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_ing_putPartiesErrorByTypeIDAndSubID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "putPartiesErrorByTypeIDAndSubID success:{{success}}"
    }
   ]
  },
  {
   "title": "Party Domain - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_als_getPartiesByTypeAndID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_getPartiesByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "getPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_putPartiesByTypeAndID_sum{cluster=\"$cluster\"}[$__rate_interval])  / rate(moja_als_putPartiesByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_puttPartiesErrorByTypeAndID_sum{cluster=\"$cluster\"}[$__rate_interval])  / rate(moja_als_puttPartiesErrorByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "puttPartiesErrorByTypeAndID success:{{success}}"
    }
   ]
  },
  {
   "title": "Party Domain - Processing Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_als_getPartiesByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "getPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_putPartiesByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "putPartiesByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_puttPartiesErrorByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "puttPartiesErrorByTypeAndID success:{{success}}"
    }
   ]
  },
  {
   "title": "Participant Resource Metric Totals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Ing GET /participants/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(moja_als_ing_getParticipantsByTypeAndID_count{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum(moja_als_ing_getParticipantsByTypeIdAndSubID_count{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Ing POST /participants/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(moja_als_ing_postParticipantsbyTypeAndID_count{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum(moja_als_ing_postParticipantsByTypeIDAndSubID_count{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Ing POST /participants requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(moja_als_ing_postParticipantsBatch_count{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Ing DELETE /participants/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(moja_als_ing_deleteParticipantsByTypeAndID_count{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum(moja_als_ing_deleteParticipantsByTypeIDAndSubID_count{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Ing PUT /participants/* requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(moja_als_ing_putParticipantsByTypeAndID_count{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum(moja_als_ing_putParticipantsByTypeIDAndSubID_count{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Ing PUT /participants/*/error requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(moja_als_ing_putParticipantsErrorByTypeAndID_count{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum(moja_als_ing_putParticipantsErrorByTypeIDAndSubID_count{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "GET /participants/* Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(moja_als_getParticipantsByTypeAndID_count{success=\"true\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(moja_als_getParticipantsByTypeAndID_count{success=\"false\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST /participants/* Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 30 },
   "targets": [
    {
     "expr": "sum(moja_als_postParticipants_count{success=\"true\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(moja_als_postParticipants_count{success=\"false\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST BATCH /participants Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "sum(moja_als_postParticipantsBatch_count{success=\"true\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(moja_als_postParticipantsBatch_count{success=\"false\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETE /participants/* Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(moja_als_deleteParticipants_count{success=\"true\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(moja_als_deleteParticipants_count{success=\"false\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT /participants/* Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 30 },
   "targets": [
    {
     "expr": "sum(moja_als_putParticipantsByTypeAndID_count{success=\"true\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(moja_als_putParticipantsByTypeAndID_count{success=\"false\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT /participants/*/error Domain Logic - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "targets": [
    {
     "expr": "sum(moja_als_putParticipantsErrorByTypeAndID_count{success=\"true\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(moja_als_putParticipantsErrorByTypeAndID_count{success=\"false\",cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Participant Resource Performance Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Participant Handlers Ingress - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_als_ing_getParticipantsByTypeAndID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_getParticipantsByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "getParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_ing_putParticipantsByTypeAndID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_putParticipantsByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_ing_postParticipantsbyTypeAndID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_postParticipantsbyTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "postParticipantsbyTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_ing_deleteParticipantsByTypeAndID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_deleteParticipantsByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "deleteParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_ing_getParticipantsByTypeIdAndSubID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_getParticipantsByTypeIdAndSubID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "getParticipantsByTypeIdAndSubID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_ing_putParticipantsByTypeIDAndSubID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_putParticipantsByTypeIDAndSubID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putParticipantsByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_ing_postParticipantsByTypeIDAndSubID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_postParticipantsByTypeIDAndSubID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "postParticipantsByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_ing_deleteParticipantsByTypeIDAndSubID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_deleteParticipantsByTypeIDAndSubID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "deleteParticipantsByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_ing_putParticipantsErrorByTypeAndID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_putParticipantsErrorByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putParticipantsErrorByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_ing_putParticipantsErrorByTypeIDAndSubID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_ing_putParticipantsErrorByTypeIDAndSubID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putParticipantsErrorByTypeIDAndSubID success:{{success}}"
    }
   ]
  },
  {
   "title": "Participant Handler Ingress - Processing Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_als_ing_getParticipantsByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "getParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_ing_putParticipantsByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "putParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_ing_postParticipantsbyTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "postParticipantsbyTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_ing_deleteParticipantsByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "deleteParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_ing_getParticipantsByTypeIdAndSubID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "getParticipantsByTypeIdAndSubID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_ing_putParticipantsByTypeIDAndSubID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "putParticipantsByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_ing_postParticipantsByTypeIDAndSubID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "postParticipantsByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_ing_deleteParticipantsByTypeIDAndSubID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "deleteParticipantsByTypeIDAndSubID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_ing_putParticipantsErrorByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "putParticipantsErrorByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_ing_putParticipantsErrorByTypeIDAndSubID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "putParticipantsErrorByTypeIDAndSubID success:{{success}}"
    }
   ]
  },
  {
   "title": "Participant Domain - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_als_getParticipantsByTypeAndID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_getParticipantsByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "getParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_putParticipantsByTypeAndID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_putParticipantsByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_putParticipantsErrorByTypeAndID_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_putParticipantsErrorByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "putParticipantsErrorByTypeAndID success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_postParticipants_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_postParticipants_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "postParticipants success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_postParticipantsBatch_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_postParticipantsBatch_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "postParticipantsBatch success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_deleteParticipants_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_deleteParticipants_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "deleteParticipants success:{{success}}"
    }
   ]
  },
  {
   "title": "Participants Domain - Processing Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_als_getParticipantsByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "getParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_putParticipantsByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "putParticipantsByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_putParticipantsErrorByTypeAndID_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "putParticipantsErrorByTypeAndID success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_postParticipants_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "postParticipants success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_postParticipantsBatch_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "postParticipantsBatch success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_postParticipantsBatch_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "deleteParticipants success:{{success}}"
    }
   ]
  },
  {
   "title": "Participant Egress - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_als_egress_getParticipantEndpoint_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_egress_getParticipantEndpoint_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (endpointType,success)",
     "legendFormat": "getParticipantEndpoint {{endpointType}} success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_egress_sendRequestToParticipant_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_egress_sendRequestToParticipant_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (endpointType,success)",
     "legendFormat": "sendRequestToParticipant {{endpointType}} success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_als_egress_validateParticipant_sum{cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_als_egress_validateParticipant_count{cluster=\"$cluster\"}[$__rate_interval]) >=0) by (success)",
     "legendFormat": "validateParticipant success:{{success}}"
    }
   ]
  },
  {
   "title": "Participant Egress - Processing Per Second",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(moja_als_egress_getParticipantEndpoint_count{cluster=\"$cluster\"}[$__rate_interval])) by (success, endpointType)",
     "legendFormat": "getParticipantEndpoint {{endpointType}} success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_egress_sendRequestToParticipant_count{cluster=\"$cluster\"}[$__rate_interval])) by (success, endpointType)",
     "legendFormat": "sendRequestToParticipant {{endpointType}} success:{{success}}"
    },
    {
     "expr": "sum(rate(moja_als_egress_validateParticipant_count{cluster=\"$cluster\"}[$__rate_interval])) by (success)",
     "legendFormat": "validateParticipant {{endpointType}} success:{{success}}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "ALS Total CPU Usage",
   "type": "gauge",
   "description": "ALS Total CPU Usage",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod=~'.*account-lookup.*',cluster=\"$cluster\"}[2m])) * 100"
    }
   ]
  },
  { "title": "Resource Usage by Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "ALS - Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "moja_als_nodejs_heap_size_total_bytes{serviceName=~\"account-lookup.*\",cluster=\"$cluster\"}",
     "legendFormat": "heap_total-{{instance}} {{kubernetes_pod_name}}"
    },
    {
     "expr": "moja_als_nodejs_heap_size_used_bytes{serviceName=~\"account-lookup.*\",cluster=\"$cluster\"}",
     "legendFormat": "heap_used-{{instance}} {{kubernetes_pod_name}}"
    },
    {
     "expr": "moja_als_nodejs_external_memory_bytes{serviceName=~\"account-lookup.*\",cluster=\"$cluster\"}",
     "legendFormat": "ext_memory-{{instance}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "ALS  -  CPU Usage in Seconds by Pod",
   "type": "timeseries",
   "description": "ALS  -  CPU Usage in Seconds by Pod",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(moja_als_process_cpu_seconds_total{serviceName=~\"account-lookup.*\",cluster=\"$cluster\"}[30s]) * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "ALS - # Nodes for each Components",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*account-lookup.*\",cluster=\"$cluster\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "ALS  - Event Loop Lag in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(moja_als_nodejs_eventloop_lag_seconds{serviceName=~\"account-lookup.*\",cluster=\"$cluster\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}