{
 "title": "mojaloop-central-ledger",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_uname_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current OP/s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transfers Prepares / sec",
   "type": "stat",
   "description": "Transfers Prepares / sec",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(moja_cl_transfer_prepare_count{serviceName=~\"central-handler-prepare|central-service\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Transfers Prepare / sec"
    }
   ]
  },
  {
   "title": "Transfer Positions / sec",
   "type": "stat",
   "description": "Transfer Positions / sec",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(moja_cl_transfer_position_count{serviceName=~\"central-handler-position|central-service\", cluster=\"$cluster\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Transfers Fullfills / sec",
   "type": "stat",
   "description": "Transfers Fullfills / sec",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(moja_cl_transfer_fulfil_count{serviceName=~\"central-handler-fulfil|central-service\", cluster=\"$cluster\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Central Ledger Lag by Consumer Group",
   "type": "timeseries",
   "description": "Central Ledger Lag by Consumer Group",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"topic-.*\", consumergroup=~\"cl-group-.*\",  cluster=\"$cluster\"}) by (consumergroup, topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Central-Service - Processed per sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(moja_cl_transfer_prepare_count{serviceName=~\"central-handler-prepare|central-service\", cluster=\"$cluster\"}[$__rate_interval])) by (app_kubernetes_io_name, success, instance)",
     "legendFormat": "{{instance}} {{app_kubernetes_io_name}} - prepare - success:{{success}}"
    },
    {
     "expr": "sum(irate(moja_cl_transfer_position_count{serviceName=~\"central-handler-position|central-service\", cluster=\"$cluster\"}[$__rate_interval])) by (app_kubernetes_io_name, action, success, instance)",
     "legendFormat": "{{instance}} {{app_kubernetes_io_name}} - position {{action}} - success:{{success}}"
    },
    {
     "expr": "sum(irate(moja_cl_transfer_position_count{serviceName=~\"central-handler-position|central-service\", cluster=\"$cluster\"}[$__rate_interval])) by (app_kubernetes_io_name, success, instance)",
     "legendFormat": "{{instance}} {{app_kubernetes_io_name}}  Avg - success:{{success}}"
    },
    {
     "expr": "sum(irate(moja_cl_transfer_fulfil_count{serviceName=~\"central-handler-fulfil|central-service\", cluster=\"$cluster\"}[$__rate_interval])) by (app_kubernetes_io_name, success, instance)",
     "legendFormat": "{{instance}} {{app_kubernetes_io_name}} - fulfil - success:{{success}}"
    }
   ]
  },
  {
   "title": "Central-Service - Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(moja_cl_transfer_prepare_sum{serviceName=~\"central-handler-prepare|central-service\", cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_cl_transfer_prepare_count{serviceName=~\"central-handler-prepare|central-service\", cluster=\"$cluster\"}[$__rate_interval]) >=0) by (kubernetes_pod_name, success, instance)",
     "legendFormat": "Transfer Prepare - {{kubernetes_pod_name}} {{instance}}  success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_cl_transfer_position_sum{serviceName=~\"central-handler-position|central-service\", cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_cl_transfer_position_count{serviceName=~\"central-handler-position|central-service\", cluster=\"$cluster\"}[$__rate_interval]) >=0) by (kubernetes_pod_name, success, instance)",
     "legendFormat": "Transfer Position - {{kubernetes_pod_name}} {{instance}} success:{{success}}"
    },
    {
     "expr": "avg(rate(moja_cl_transfer_fulfil_sum{serviceName=~\"central-handler-fulfil|central-service\", cluster=\"$cluster\"}[$__rate_interval]) / rate(moja_cl_transfer_fulfil_count{serviceName=~\"central-handler-fulfil|central-service\", cluster=\"$cluster\"}[$__rate_interval]) >=0) by (kubernetes_pod_name, success, instance)",
     "legendFormat": "Transfer Fulfil - {{kubernetes_pod_name}} {{instance}}  success:{{success}}"
    }
   ]
  },
  {
   "title": "CPU Usage by App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Central Services Total CPU Usage",
   "type": "gauge",
   "description": "Central Services Total CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger.*', cluster=\"$cluster\"}[2m]))"
    }
   ]
  },
  {
   "title": "Transfer Prepare Handler CPU Usage",
   "type": "gauge",
   "description": "Transfer Prepare Handler CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger-handler-transfer-prepare.*', cluster=\"$cluster\"}[2m]))"
    }
   ]
  },
  {
   "title": "Transfer Position Handler CPU Usage",
   "type": "gauge",
   "description": "Transfer Position Handler CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger-handler-transfer-position.*', cluster=\"$cluster\"}[2m]))"
    }
   ]
  },
  {
   "title": "Transfer Fulfil Handler CPU Usage",
   "type": "gauge",
   "description": "Transfer Fulfil Handler CPU Usage",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{pod_name=~'.*centralledger-handler-transfer-fulfil.*', cluster=\"$cluster\"}[2m]))"
    }
   ]
  },
  {
   "title": "Resource Usage by Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Central Services - Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "moja_cl_nodejs_heap_space_size_available_bytes{serviceName=~\"central-handler.*|central-service\", cluster=\"$cluster\"}",
     "legendFormat": "heap_space_free-{{kubernetes_pod_name}} {{serviceName}} {{space}}"
    },
    {
     "expr": "moja_cl_nodejs_heap_space_size_used_bytes{serviceName=~\"central-handler.*|central-service\", cluster=\"$cluster\"}",
     "legendFormat": " heap_space_used-{{kubernetes_pod_name}} {{serviceName}} {{space}} "
    },
    {
     "expr": "moja_cl_nodejs_heap_size_total_bytes{serviceName=~\"central-handler.*|central-service\", cluster=\"$cluster\"}",
     "legendFormat": "heap_total-{{kubernetes_pod_name}} {{serviceName}}"
    },
    {
     "expr": "moja_cl_nodejs_heap_size_used_bytes{serviceName=~\"central-handler.*|central-service\", cluster=\"$cluster\"}",
     "legendFormat": " heap_used-{{kubernetes_pod_name}} {{serviceName}}"
    },
    {
     "expr": "moja_cl_nodejs_external_memory_bytes{serviceName=~\"central-handler.*|central-service\", cluster=\"$cluster\"}",
     "legendFormat": "ext_memory-{{kubernetes_pod_name}} {{serviceName}}"
    }
   ]
  },
  {
   "title": "Central-Service  - CPU Usage in Seconds by Pod",
   "type": "timeseries",
   "description": "Central-Service  - CPU Usage in Seconds by Pod",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(moja_cl_process_cpu_seconds_total{serviceName=~\"central.*\", cluster=\"$cluster\"}[$__rate_interval]) * 100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Central-Service  - Event Loop Lag in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(moja_cl_nodejs_eventloop_lag_seconds{serviceName=~\"central.*\", cluster=\"$cluster\"}) by (serviceName, instance)",
     "legendFormat": "{{serviceName}} {{instance}}"
    }
   ]
  },
  {
   "title": "Central-Service - # Pods for each Components",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=~\".*-centralledger-.*|central-service\", cluster=\"$cluster\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}