FROM ubuntu:20.04
RUN apt-get update && apt-get install -y software-properties-common curl gnupg2 && \
  curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - && \
  apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && \
  apt-get update && apt-get install -y \
  vault={{ vault_image_version }}.0-1 jq curl && \
  setcap cap_ipc_lock= /usr/bin/vault
COPY init.sh ./
CMD ./init.sh