FROM caddy:{{ vault_caddy_image_version }}-builder as builder

RUN xcaddy build {{ vault_caddy_image_version }} \
    --with github.com/caddy-dns/route53@v{{ vault_r53_image_version }}

FROM caddy:{{ vault_caddy_image_version }}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
RUN /usr/bin/caddy version
RUN /usr/bin/caddy list-modules --skip-standard --versions