# add user specific settings
---
- name: add user to group
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: microk8s
    append: yes
  with_items: "{{ users }}"
  loop_control:
    loop_var: user
    label: "{{ user }}"

- name: Create .kube folder for the user
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0750
  with_items: "{{ users }}"
  loop_control:
    loop_var: user
    label: "{{ user }}"

- name: Get current kubectl config
  become: true
  ansible.builtin.shell: microk8s config
  register: microk8s_config
  changed_when: false

- name: create kubectl config
  become: true
  ansible.builtin.copy:
    content: "{{ microk8s_config.stdout }}"
    dest: "{{ '~' + user + '/.kube/config' | expanduser }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0600'
  with_items: "{{ users }}"
  loop_control:
    loop_var: user
    label: "{{ user }}"

- name: reaffirm permission on files
  become: true
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: yes
    mode: 0750
  with_items: "{{ users }}"
  loop_control:
    loop_var: user
    label: "{{ user }}"