apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: XXX
  AWS_REGION: XXX
  AWS_SECRET_ACCESS_KEY: XXX
  cloud: XXX
kind: Secret
metadata:
  annotations:
    reconcile.external-secrets.io/data-hash: 885e8e7ac8761b17d7f482a9a6daff1a
  creationTimestamp: "2025-06-16T12:39:01Z"
  labels:
    reconcile.external-secrets.io/created-by: 9ef530b172e57ad99be10c8f26d22120
    reconcile.external-secrets.io/managed: "true"
  name: cloud-credentials
  namespace: velero
  ownerReferences:
  - apiVersion: external-secrets.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: cloud-credentials
    uid: acec95b4-7ef5-45eb-ac98-f1596c49e9d9
  resourceVersion: "91488"
  uid: 3452a3ef-bfd2-4781-8dec-802823f58fec
type: Opaque
